version: '3.6'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
  app:
    build: .
    container_name: app
    ports:
      - '8080:8080'